# Generated by Django 3.2 on 2022-03-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubCollections', to='store.collection'),
        ),
    ]
