# Generated by Django 3.2 on 2022-03-21 09:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_type'),
        ('store', '0004_alter_proditemwishlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWishList',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreItemWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_item_wish', to='store.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_item_wish', to='store.storewishlist')),
            ],
        ),
    ]
