# Generated by Django 3.2 on 2022-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_subcollection_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
