# Generated by Django 3.2 on 2022-03-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220321_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
