# Generated by Django 3.2 on 2022-03-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_sub_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_collection',
        ),
    ]
