# Generated by Django 3.2 on 2022-03-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_sub_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcollection',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='product',
            name='sub_collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.subcollection'),
            preserve_default=False,
        ),
    ]
