# Generated by Django 3.2 on 2022-03-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220316_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.subcollection'),
        ),
    ]
