# Generated by Django 3.2 on 2022-04-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220405_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='order_count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
