# Generated by Django 3.2 on 2022-04-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220411_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subcollection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
