# Generated by Django 3.2 on 2022-04-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20220415_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeimage',
            name='brand_image',
        ),
    ]
