# Generated by Django 3.2 on 2022-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20220426_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
