# Generated by Django 3.2 on 2022-04-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=80)),
                ('num_order', models.BigIntegerField()),
                ('date_order', models.DateField()),
                ('slug_produit_retour', models.CharField(max_length=255)),
                ('cause', models.TextField()),
                ('image', models.ImageField(upload_to='store/prod_retour')),
                ('accept', models.BooleanField(default=False)),
                ('refuse', models.BooleanField(default=False)),
            ],
        ),
    ]
