# Generated by Django 3.2 on 2022-04-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_demanderetour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcollection',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
