# Generated by Django 3.2 on 2022-04-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_subcollection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.TextField(),
        ),
    ]
