# Generated by Django 3.2 on 2022-04-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_collection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcollection',
            name='title',
            field=models.TextField(),
        ),
    ]
