# Generated by Django 3.2 on 2022-04-28 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20220426_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanderetour',
            name='placed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcollection',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
