# Generated by Django 3.2 on 2022-04-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20220428_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demanderetour',
            old_name='image',
            new_name='image_facture',
        ),
        migrations.AddField(
            model_name='demanderetour',
            name='image_produit',
            field=models.ImageField(blank=True, null=True, upload_to='store/prod_retour'),
        ),
    ]
