# Generated by Django 3.2 on 2022-04-30 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20220428_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proditemwishlist',
            name='note',
            field=models.IntegerField(default=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
