# Generated by Django 3.2 on 2022-05-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_alter_proditemwishlist_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprod',
            name='size',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
