# Generated by Django 3.2 on 2022-05-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20220504_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='msg',
            field=models.CharField(default='', max_length=255),
        ),
    ]
