# Generated by Django 3.2 on 2022-05-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_remove_order_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='display',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='msg',
        ),
    ]
