# Generated by Django 3.2 on 2022-05-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_auto_20220505_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='msg',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='store',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='msg',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='store',
            field=models.BigIntegerField(default=1),
        ),
    ]
