# Generated by Django 3.2 on 2022-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_auto_20220505_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='msg',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='msg',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
