# Generated by Django 3.2 on 2022-05-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_auto_20220505_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.AddField(
            model_name='product',
            name='price_with_promotion',
            field=models.IntegerField(default=0),
        ),
    ]
