# Generated by Django 3.2 on 2022-05-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_auto_20220506_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_with_promotion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
