# Generated by Django 3.2 on 2022-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_product_price_with_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_with_promotion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
