# Generated by Django 3.2 on 2022-05-07 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20220507_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proditemwishlist',
            name='note',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='storeitemwishlist',
            name='note',
            field=models.IntegerField(blank=True, default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
