# Generated by Django 3.2 on 2022-05-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storereview',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeimage',
            name='store_image',
            field=models.ImageField(default='store/storee/2.jpeg', upload_to='store/storee'),
        ),
    ]
