# Generated by Django 3.2 on 2022-03-09 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220309_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.type'),
        ),
    ]
