# Generated by Django 3.2 on 2022-03-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
